version: 2

project_name: pg

before:
  hooks:
    - go mod tidy
    - mkdir -p build
    - sh -c "scripts/generate_release_notes {{.Version}} >build/release_notes.md"
    - mkdir -p build/completions
    - sh -c "go run ./cmd/pg -completion-script bash >build/completions/pg.bash"
    - sh -c "go run ./cmd/pg -completion-script zsh >build/completions/_pg"
    - sh -c "go run ./cmd/pg -completion-script fish >build/completions/pg.fish"

builds:
  - main: ./cmd/pg
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
archives:
  - files:
      - CHANGELOG.md
      - LICENSE
      - LICENSES/*
      - README.md
      - src: build/completions
        dst: completions
      - docs

release:
  name_template: "{{.ProjectName}} {{.Version}}"

snapshot:
  version_template: "{{ .Version }}-next"
