#!/usr/bin/env sh
#
# Prints the release notes for a given version to stdout
# The release notes are composed of a changelog and installation instructions.
# The changes in the changelog are the ones from the latest version in CHANGELOG.md. The version
# argument does not affect which changes are included.
# Arguments:
#     $1: version

set -eu

version=${1:-}
if [ -z "$version" ]; then
    printf 'error: missing required version argument\n' >&2
    exit 2
fi

printf '## Changelog\n'

awk '
    /^## / {
        if (/Unreleased/) next
        if (found) exit
        found = 1
        next
    }
    found
' CHANGELOG.md

printf '## Installation\n'
printf '### %s\n' "$version"
printf '```sh\n'
printf 'curl -fsSL https://raw.githubusercontent.com/marcuscaisey/playground/HEAD/scripts/install.sh \\\n'
printf '    | sudo sh -s -- -v %s\n' "$version"
printf '```\n'
printf '### Latest Version\n'
printf '```sh\n'
printf 'curl -fsSL https://raw.githubusercontent.com/marcuscaisey/playground/HEAD/scripts/install.sh \\\n'
printf '    | sudo sh\n'
printf '```\n'
printf 'See the [README](https://github.com/marcuscaisey/playground#installation) for more details.\n'
