name: CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  check-markdown-man-page:
    name: Check Markdown Man Page
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v7
      - name: Install mandoc
        run: sudo apt-get update && sudo apt-get install mandoc
      - name: Run markdown man page check
        run: scripts/check_markdown_man_page

  test-goreleaser-release:
    name: Test GoReleaser Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v7
      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
      - name: Run GoReleaser release
        uses: goreleaser/goreleaser-action@v7
        with:
          version: "~> v2"
          args: release --snapshot --clean
